# Generated by Django 2.0.1 on 2018-01-31 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_publications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publications',
            old_name='created_date',
            new_name='date',
        ),
    ]
