# Generated by Django 2.0.1 on 2018-02-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_auto_20180131_1704'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.RenameField(
            model_name='publications',
            old_name='text',
            new_name='publishing_house',
        ),
        migrations.AddField(
            model_name='publications',
            name='location',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publications',
            name='pages',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publications',
            name='date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
    ]
