# Generated by Django 2.0.1 on 2018-02-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_auto_20180203_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='date',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
    ]
