# Generated by Django 2.0.1 on 2018-02-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_auto_20180203_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('initials', models.SlugField(max_length=12)),
                ('is_lab_employee', models.BooleanField(default=True)),
            ],
        ),
    ]
