# Generated by Django 2.0.1 on 2018-02-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='name',
            new_name='surname',
        ),
        migrations.AlterField(
            model_name='authors',
            name='initials',
            field=models.CharField(max_length=6),
        ),
    ]
