# Generated by Django 2.0.1 on 2018-02-06 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0007_auto_20180206_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.Authors'),
        ),
    ]
