# Generated by Django 2.0.1 on 2018-02-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0009_auto_20180211_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publications',
            options={'ordering': ['-pk']},
        ),
    ]
