# Generated by Django 2.0.1 on 2018-02-06 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0009_auto_20180206_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publications',
            name='author',
        ),
        migrations.AddField(
            model_name='publications',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='News.Authors'),
            preserve_default=False,
        ),
    ]
